import { Changa } from 'next/font/google'
import './globals.css'
import { Metadata } from 'next'
const inter = Changa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#1a1c1f] text-white`}>
        {children}
      </body>
    </html>
  )
}
